### ISSUE TITLE
Add a logo for Urban Bangla

### ISSUE THREAD

**Issue by zihadbappy** [zihadbappy/UrbanBangla#1]
Add a new logo in _static/styles/logo_ directory and name it _new_logo.png_

**Comment by bhavy2202** [comment]
Please assign me

**Comment by zihadbappy** [comment]
> Please assign me

Done. Goodluck

**Comment by bhavy2202** [comment]
can you add hacktober tag in this issue please?

**Comment by zihadbappy** [comment]
> can you add hacktober tag in this issue please?

Sure thing. Thanks for the contribution
